http {
  host = 0.0.0.0, host = ${?CARDS_HTTP_HOST}
  port = 8080, port = ${?CARDS_HTTP_PORT}
  # Comma separated list of allowed origins for CORS or "*" to allow all origins
  cors-allowed-origins = "*", cors-allowed-origins = ${?CARDS_HTTP_CORS_ALLOWED_ORIGINS}
}

database {
  host = localhost, host = ${?CARDS_DB_HOST}
  port = 5432, port = ${?CARDS_DB_PORT}
  user = cards, user = ${?CARDS_DB_USER}
  password = password, password = ${?CARDS_DB_PASSWORD}
  db = cards, db = ${?CARDS_DB_NAME}
  max-session = 10, max-session = ${?CARDS_DB_MAX_SESSION}
}

auth {
  secret-key = "SECRET_KEY_REPLACE_ME!!!", secret-key = ${?CARDS_AUTH_SECRET_KEY}
  exp = 1 hour, exp = ${?CARDS_AUTH_EXP}
}
