client {
  api-uri = "http://localhost:8080", api-uri = ${?CARDS_CLI_API_URI}
  ws-uri = "ws://localhost:8080", ws-uri = ${?CARDS_CLI_WS_URI}
}

auth {
  user-name = "Yo", user-name = ${?CARDS_CLI_USER_NAME}
  password = ${CARDS_CLI_PASSWORD}
}
