name: cards_dev_env
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: cards
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cards
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  pgdata:
